# Generated by Django 5.2 on 2026-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('JSS 1A', 'JSS 1A'), ('JSS 1B', 'JSS 1B'), ('JSS 1C', 'JSS 1C'), ('JSS 2A', 'JSS 2A'), ('JSS 2B', 'JSS 2B'), ('JSS 2C', 'JSS 2C'), ('JSS 3A', 'JSS 3A'), ('JSS 3B', 'JSS 3B'), ('JSS 3C', 'JSS 3C'), ('SS 1A', 'SS 1A'), ('SS 1B', 'SS 1B'), ('SS 1C', 'SS 1C'), ('SS 2A', 'SS 2A'), ('SS 2B', 'SS 2B'), ('SS 2C', 'SS 2C'), ('SS 3A', 'SS 3A'), ('SS 3B', 'SS 3B'), ('SS 3C', 'SS 3C')], max_length=20),
        ),
    ]
