# Generated by Django 5.2 on 2026-07-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_student_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
    ]
