# Generated by Django 5.2 on 2026-07-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='class_name',
        ),
    ]
