# Generated by Django 5.2 on 2026-08-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
