# Generated by Django 5.2 on 2026-07-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='staff_no',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
