# Generated by Django 5.2 on 2026-08-02 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='timetableslot',
            options={'ordering': ['day', 'period__number']},
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.period'),
        ),
    ]
