# Generated by Django 5.2 on 2026-07-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='session',
            field=models.CharField(default='2026/2027', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.CharField(choices=[('FIRST', 'First Term'), ('SECOND', 'Second Term'), ('THIRD', 'Third Term')], max_length=10),
        ),
    ]
